import dedent from "dedent";

export default {
    api: {
        'clear-cache': 'Clear Cache',
        'cache-cleared': {
            header: 'Cache Cleared',
            content: 'Cache has been cleared. Future downloads will fetch the latest data from the server',
        },
    },
    novel: {
        download: 'Download Epub',
    },
    series: {
        download: 'Download Epub',
    },
    custom: {
        download: 'Batch Download Novels',
        input: {
            header: 'Batch Download Novels',
            content: 'Please enter the links or IDs of the novels to download, one per line, or separate multiple links/IDs with spaces or commas in a single line:',
        },
        invalidInput: {
            header: 'Invalid Input Format',
            content: 'Please check the input format.\nEnter one novel link or ID per line, or separate multiple links/IDs with spaces or commas in a single line.',
        },
        fetchingData: 'Fetching novel data',
        filename: {
            header: 'Batch Download Novels',
            content: 'Please enter the filename for the saved Epub:',
        },
    },
    downloader: {
        epub: {
            link: 'Novel link: <a href="{link}">{link}</a>',
            notes: dedent`
                <div>EPUB generated from: <a href="{link}">{link}</a></div>
                <div>Generated by <a href="{scriptUrl}">{scriptName}</a> author <a href="{authorUrl}">{authorName}</a></div><br>
                <div>Copyright belongs to the article author. Please comply with relevant legal requirements while reading and distributing this file.</div>
            `,
        },
        progress: {
            'novel-api': 'Loading novel data',
            'series-api': 'Loading series data',
            'series-index': 'Loading series index',
            'series-novel': 'Loading series novels',
            cover: 'Loading cover image',
            images: 'Loading images',
            generate: 'Generating Epub file',
            save: 'Saving Epub file',
        },
        error: {
            message: 'An error occurred during the download, please try again or report it to the developer',
            header: 'Download Error',
        },
    },
    popup: {
        dialog: {
            alert: {
                header: 'Notice',
                buttons: {
                    ok: 'OK',
                },
            },
            prompt: {
                header: 'Please enter',
                buttons: {
                    ok: 'OK',
                    cancel: 'Cancel',
                }
            },
        },
    },
};
