import dedent from "dedent";

export default {
    components: {
        'multi-input': {
            invalid: 'Invalid input',
        },
    },
    api: {
        'clear-cache': 'Clear Cache',
        'cache-cleared': {
            header: 'Cache Cleared',
            content: 'Cache has been cleared. Future downloads will fetch the latest data from the server',
        },
    },
    novel: {
        download: 'Download Epub',
    },
    series: {
        download: 'Download Epub',
    },
    custom: {
        download: 'Batch Download Novels',
        input: {
            header: 'Batch Download Novels',
            content: 'Please enter the link or ID of the novel to download\nPress Enter, Space, or Comma after input to add to the list:',
            buttons: {
                ok: 'OK',
                cancel: 'Cancel',
            },
            invalid: {
                common: 'Invalid input format',
                duplicate: 'Already added',
            },
            preview: {
                error: 'Failed to load novel data',
                loading: 'Loading...',
            }
        },
        'novel-api-error': {
            header: 'Batch Download Novels',
            content: 'Error fetching novel data:\nPlease check your input and network connection.',
        },
        'invalid-input': {
            header: 'Invalid Input Format',
            content: 'Please check the input format.\nEnter the link or ID of the novel, press Enter or Space after input to add to the list.',
        },
        'fetching-data': 'Fetching novel data',
        filename: {
            header: 'Batch Download Novels',
            content: 'Please enter the filename for the saved Epub:',
        },
    },
    downloader: {
        epub: {
            link: 'Novel link: <a href="{link}">{link}</a>',
            notes: dedent`
                <div>EPUB generated from: <a href="{link}">{link}</a></div>
                <div>Generated by <a href="{scriptUrl}">{scriptName}</a> author <a href="{authorUrl}">{authorName}</a></div><br>
                <div>Copyright belongs to the article author. Please comply with relevant legal requirements while reading and distributing this file.</div>
            `,
        },
        progress: {
            'novel-api': 'Loading novel data',
            'series-api': 'Loading series data',
            'series-index': 'Loading series index',
            'series-novel': 'Loading series novels',
            cover: 'Loading cover image',
            images: 'Loading images',
            generate: 'Generating Epub file',
            save: 'Saving Epub file',
        },
        error: {
            message: 'An error occurred during the download, please try again or report it to the developer',
            header: 'Download Error',
        },
    },
    popup: {
        dialog: {
            dialog: {
                header: 'Default Title',
                buttons: {
                    ok: 'OK',
                }
            },
            alert: {
                header: 'Notice',
                buttons: {
                    ok: 'OK',
                },
            },
            prompt: {
                header: 'Please enter',
                buttons: {
                    ok: 'OK',
                    cancel: 'Cancel',
                }
            },
        },
    },
};
